version: '3'
services:
  ambassador_backend:
    build: .
    image: antoniopapa/ambassador:0.0.1
    environment:
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISMS: PLAIN
      GROUP_ID: myGroup
      KAFKA_TOPIC:
      DB_HOST:
      DB_DATABASE:
      DB_PORT: 3306
      DB_USERNAME:
      DB_PASSWORD:
      USERS_MS: http://users-ms:8000
      REDIS_URL: redis://redis:6379/0
    command: >
      sh -c "python manage.py wait_for_db
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8003:8000

  ambassador_queue:
    build: .
    environment:
      BOOTSTRAP_SERVERS:
      SECURITY_PROTOCOL: SASL_SSL
      SASL_USERNAME:
      SASL_PASSWORD:
      SASL_MECHANISMS: PLAIN
      GROUP_ID: myGroup
      KAFKA_TOPIC:
      DB_HOST:
      DB_DATABASE:
      DB_PORT: 3306
      DB_USERNAME:
      DB_PASSWORD:
      USERS_MS: http://users-ms:8000
      REDIS_URL: redis://redis:6379/0
    image: antoniopapa/ambassador:0.0.1
    command: >
      sh -c "python manage.py wait_for_db
      && python consumer.py"

  redis:
    image: redis
    ports:
      - 6379:6379
